# Generated by Django 5.2.11 on 2026-02-15 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_skill_profile_my_story_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
