# Generated by Django 5.2.11 on 2026-02-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_post_published_at_post_status_alter_post_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
