# Generated by Django 5.2.11 on 2026-02-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_alter_post_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shortened_url_code',
        ),
        migrations.AddField(
            model_name='post',
            name='short_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
