# Generated by Django 5.2.11 on 2026-02-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_remove_post_shortened_url_code_post_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/post-1jpg', upload_to='blog'),
        ),
    ]
