# Generated by Django 5.2.11 on 2026-02-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/post-1.jpg', upload_to='blog'),
        ),
    ]
