# Generated by Django 5.2.11 on 2026-02-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0009_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
