# Generated by Django 5.2.11 on 2026-02-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0010_post_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
