# Generated by Django 5.2.11 on 2026-02-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0012_alter_newsletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='rg', unique=True),
            preserve_default=False,
        ),
    ]
