# Generated by Django 5.2.11 on 2026-02-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0013_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
