# Generated by Django 5.2.11 on 2026-02-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0015_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
