# Generated by Django 5.2.11 on 2026-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0018_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estimated_reading_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
